name: Stage natours-backend

on:
  push:
    branches:
      - dev

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code and Restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USERNAME }}
          key: ${{secrets.SERVER_SSH_KEY}}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            set -e
            echo 'Going into natours directory...'
            cd /home/ubuntu/Staging/natours-ts

            echo 'Pulling code from dev branch...'
            git pull origin dev

            echo 'Installing dependencies...'
            npm install

            echo 'Restarting pm2 process...'
            pm2 restart natours-ts
