name: Stage natours-backend

on:
  push:
    branches:
      - dev

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_SSH_USERNAME }}
          key: ${{secrets.SERVER_SSH_KEY}}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            set -e
            # export PATH=/usr/local/bin:$PATH
            cd /home/ubuntu/Staging/natours-ts
            sh ./pull.sh
